version: "3.5"

networks:
  inception:
    name: inception

volumes:
  wp:
    driver: local
    name: wp
    driver_opts:
      type: none
      o: bind
      device: /$HOME/data/wordpress
  db:
    driver: local
    name: db
    driver_opts:
      type: none
      o: bind
      device: /$HOME/data/mariadb

services:
  nginx:
    build: ./requirements/nginx
    container_name: nginx
    env_file:
      - .env
    depends_on:
      - wordpress
      - mariadb
    ports:
      - "443:443"
    volumes:
      - wp:/var/www/html
    networks:
      - inception
    restart: unless-stopped
  wordpress:
    build: ./requirements/wordpress
    container_name: wordpress
    env_file:
      - .env
    depends_on:
      - mariadb
    volumes:
      - wp:/var/www/html
    networks:
      - inception
    restart: unless-stopped
  mariadb:
    build: ./requirements/mariadb
    container_name: mariadb
    env_file:
      - .env
    volumes:
      - db:/var/lib/mysql
    networks:
      - inception
    restart: unless-stopped
